# Generated by Django 6.0.4 on 2026-09-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livreurs_app', '0001_initial'),
        ('zones_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_depart', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_depart', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude_arrivee', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_arrivee', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description_colis', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de livreur'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_client', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='livreurs_app.livreur')),
                ('zone_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_arrivee', to='zones_app.zone')),
                ('zone_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_depart', to='zones_app.zone')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='commandes_a_statut_f79ac0_idx')],
            },
        ),
    ]
