# Generated by Django 6.0.4 on 2026-09-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos')),
                ('palier', models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profil', to=settings.AUTH_USER_MODEL)),
                ('zones_couvertes', models.ManyToManyField(blank=True, related_name='entreprises', to='zones_app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='MembreAdminsEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_admin', to='entreprises_app.entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre_admin_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
