# Generated by Django 6.0.4 on 2026-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ville', 'quartier'],
                'unique_together': {('pays', 'ville', 'quartier')},
            },
        ),
    ]
