# Generated by Django 6.0.4 on 2026-09-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes_app', '0001_initial'),
        ('livreurs_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='commandes_app.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='livreurs_app.livreur')),
            ],
        ),
    ]
