# Generated by Django 6.0.4 on 2026-09-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises_app', '0001_initial'),
        ('zones_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('velo', 'Vélo'), ('voiture', 'Voiture'), ('pied', 'À pied')], max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nb_livraisons', models.PositiveIntegerField(default=0)),
                ('photo_cni_recto', models.ImageField(blank=True, null=True, upload_to='livreurs/cni/%Y/%m/')),
                ('photo_cni_verso', models.ImageField(blank=True, null=True, upload_to='livreurs/cni/%Y/%m/')),
                ('photo_selfie', models.ImageField(blank=True, null=True, upload_to='livreurs/selfies/%Y/%m/')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='livreurs/profils/%Y/%m/')),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs', to='entreprises_app.entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profil', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs_verifies', to=settings.AUTH_USER_MODEL)),
                ('zone_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs_presents', to='zones_app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='PositionLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_positions', to='livreurs_app.livreur')),
            ],
            options={
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['livreur', '-horodatage'], name='livreurs_ap_livreur_ebe7f8_idx')],
            },
        ),
    ]
